FAIL
run: write() returned 0 instead of 239: FAILED
